dist: trusty
sudo: required
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-8
    packages:
      - cmake
      - g++-8
      - libgtest-dev
      - build-essential
script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - sudo mkdir /usr/src/gtest/build -p
  - cd /usr/src/gtest/build
  - ls -la ..
  - sudo cmake ..
  - sudo ls -Rla ..
  - sudo ln -s *.a /usr/lib
  - cd -
  - echo $LD_LIBRARY_PATH
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  # Go to working directory
  - cd ecs
  #Get compiler version
  - make test -k -j
