dist: trusty
sudo: required
language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-8
    packages:
      - cmake
      - g++-8
      - libgtest-dev
      - build-essential
script:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  # Build and intall GTest libraries
  - sudo mkdir /usr/src/gtest/build -p
  - cd /usr/src/gtest/build
  - sudo cmake ..
  - sudo make
  - sudo cp *.a /usr/local/lib
  - cd -
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  # Go to working directory
  - cd ecs
  - sudo make test -k -j
  - ./unit-tester