language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-8
    packages:
      - g++-8
      - clang++-8
      - gcc-8
      - clang-8
      - libgtest-dev
script: cd ecs/ && g++ -v
